name: Unit Test and Generate APK
on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Cache gradle
      - name: Cache Gradle and wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: cache-${{ runner.os }}-${{ matrix.jdk }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run Unit tests
        run: bash ./gradlew test --stacktrace
        
      - name: Run Gradle Lint
        run: bash ./gradlew lint
  apk:
      name: Generate APK
      needs: test
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: Setup Java JDK
          uses: actions/setup-java@v3.8.0
          with:
            java-version: 11
            distribution: 'temurin'

        - name: Grant Permission to Execute
          run: chmod +x gradlew

        - name: Build debug APK
          run: bash ./gradlew assembleDebug --stacktrace

        - name: Upload APK to Github Artifacts
          uses: actions/upload-artifact@v3.1.1
          with:
            name: app
            path: app/build/outputs/apk/debug/app-debug.apk
